# Generated by Django 3.0.5 on 2020-04-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
