# Generated by Django 2.2.12 on 2020-05-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='token',
        ),
    ]
