# Generated by Django 2.2.12 on 2020-05-14 23:32

from django.db import migrations
import djongo.models.fields
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='userdata',
            name='pages',
            field=djongo.models.fields.ArrayField(default=[], model_container=home.models.Page),
            preserve_default=False,
        ),
    ]
